### ISSUE TITLE
Protected paths er ikke beskyttet for brukere med en ikke godkjent HPR-rolle

### ISSUE THREAD

**Issue by mmalvik** [folkehelseinstituttet/fhi.helseid#11]
Når man bruker denne komponenten er ikke protected paths beskyttet fra personer med en ikke godkjent HPR-rolle.
F.eks om en app har satt opp tilgang til kun leger på denne måten:
```csharp
public class HprApprovals : GodkjenteHprKategoriListe
{
    public HprApprovals()
    {
        Add(Kodekonstanter.OId9060Lege);
    }
}
```

Om man da logger inn med en bruker som er sykepleier får man fortsatt tilgang beskyttede pather, f.eks index.html.
Alle API-kall vil dog gi 403 Forbidden.

Feilen ser ut til å ligge her:
https://github.com/folkehelseinstituttet/fhi.helseid/blob/6953aab87ec4fba8d178af8ac1062fc8646fb972/Fhi.HelseId/Web/ExtensionMethods/ServiceCollectionExtensions.cs#L96

Det blir ikke tatt hensyn til `HprKonfigurasjon` her.
Dersom `UseHpr` og `UseHprPolicy` er `true` burde policy for protected paths blitt satt til `Policies.GodkjentHprKategoriPolicy`.

Så lenge `UseHprNumber` er true brukes `Policies.HprNummer` uansett for disse pathene.

**Comment by robinbaxon** [comment]
Very nice find! Denne må vi fikse.
