### ISSUE TITLE
Change publish nuget to use method from Fhi.ClientCredentials

### ISSUE THREAD

**Issue by OsirisTerje** [folkehelseinstituttet/fhi.helseid#324]
See yml here: https://github.com/folkehelseinstituttet/Fhi.ClientCredentials/blob/main/.github/workflows/Fhi.ClientCredentials.Refit.Nuget.yml

Ser at også Fhi.HelseId.Refit.nuget.yml bruker den korrekte metoden.   

Fhi.HelseId og Fhi.HelseId.TestSupport bruker den ikke.

Remove the publish job used now, and replace with the corresponding job from the above. 

PS: The job used now have a tendency to fail sometimes.

**Comment by roar-andersen** [comment]
Har laget en PR: #329
