### ISSUE TITLE
Lage demo applikasjon

### ISSUE THREAD

**Issue by OsirisTerje** [folkehelseinstituttet/fhi.helseid#5]

**Comment by mmalvik** [comment]
Hi!

During our work on integrating Fhi.HelseId into our code I made a basic demo app.
It has an Angular frontend and is based on `dotnet new angular`.

@robinbaxon has seen this demo app in action and helped us with how logout should be called.

I have just pushed this to my Github here: https://github.com/mmalvik/Fhi-HelseId-Demo

I do not know whether you want the demo app in this repository or a separate one. 
Feel free to copy my demo app and use it any way you want 👍
